version: "3.8"

services:
  db:
    build: ./db
    container_name: mysql_boissons
    environment:
      MYSQL_DATABASE: db_boissons
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user_boissons
      MYSQL_PASSWORD: pass_boissons
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - volume_boissons_data:/var/lib/mysql

  web:
    build: ./web
    container_name: web_boissons
    ports:
      - "8000:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    container_name: pma_boissons
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  volume_boissons_data:
